/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tools: Tool;
    makers: Maker;
    projects: Project;
    posts: Post;
    examples: Example;
    'tool-categories': ToolCategory;
    'creation-types': CreationType;
    'maker-specialties': MakerSpecialty;
    'community-types': CommunityType;
    'news-categories': NewsCategory;
    'user-situations': UserSituation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    makers: MakersSelect<false> | MakersSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    examples: ExamplesSelect<false> | ExamplesSelect<true>;
    'tool-categories': ToolCategoriesSelect<false> | ToolCategoriesSelect<true>;
    'creation-types': CreationTypesSelect<false> | CreationTypesSelect<true>;
    'maker-specialties': MakerSpecialtiesSelect<false> | MakerSpecialtiesSelect<true>;
    'community-types': CommunityTypesSelect<false> | CommunityTypesSelect<true>;
    'news-categories': NewsCategoriesSelect<false> | NewsCategoriesSelect<true>;
    'user-situations': UserSituationsSelect<false> | UserSituationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  title: string;
  /**
   * Short one-liner (max 120 characters)
   */
  tagline?: string | null;
  /**
   * Brief summary for listings
   */
  excerpt?: string | null;
  /**
   * Full tool description
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tool logo (min 200x200px)
   */
  logo?: (number | null) | Media;
  /**
   * Official website URL
   */
  website?: string | null;
  pricingModel?: ('free' | 'freemium' | 'paid' | 'custom') | null;
  /**
   * e.g., "Free tier available, Pro from $20/mo"
   */
  pricingSummary?: string | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  useCases?:
    | (
        | 'writing'
        | 'images'
        | 'video'
        | 'audio'
        | 'code'
        | 'design'
        | 'data'
        | 'automation'
        | 'education'
        | 'business'
      )[]
    | null;
  platforms?:
    | ('web' | 'ios' | 'android' | 'mac' | 'windows' | 'linux' | 'api' | 'plugin' | 'discord' | 'slack')[]
    | null;
  keyFeatures?:
    | {
        /**
         * Lucide icon name
         */
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  stats?: {
    /**
     * e.g., "10M+", "500K"
     */
    users?: string | null;
    /**
     * Rating out of 5
     */
    rating?: number | null;
    company?: string | null;
    launchYear?: number | null;
  };
  slug: string;
  /**
   * Feature in discovery listings
   */
  featured?: boolean | null;
  toolCategory?: (number | null) | ToolCategory;
  creationTypes?: (number | CreationType)[] | null;
  userSituations?: (number | UserSituation)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-categories".
 */
export interface ToolCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Lucide icon name (e.g., "type", "image", "video")
   */
  icon?: string | null;
  /**
   * Hex color code (e.g., "#3B82F6")
   */
  color?: string | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creation-types".
 */
export interface CreationType {
  id: number;
  title: string;
  slug: string;
  /**
   * Emoji or icon name
   */
  icon?: string | null;
  tagline?: string | null;
  description?: string | null;
  /**
   * Primary color (hex)
   */
  color?: string | null;
  /**
   * Gradient end color (hex)
   */
  gradientColor?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Example prompts for this creation type
   */
  examplePrompts?:
    | {
        prompt: string;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  stats?: {
    /**
     * Number of tools in this category
     */
    toolCount?: number | null;
    /**
     * Number of projects using this type
     */
    projectCount?: number | null;
  };
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-situations".
 */
export interface UserSituation {
  id: number;
  title: string;
  slug: string;
  /**
   * Emoji
   */
  icon?: string | null;
  tagline?: string | null;
  description?: string | null;
  /**
   * Primary color (hex)
   */
  color?: string | null;
  /**
   * Accent color (hex)
   */
  accentColor?: string | null;
  avatar?: (number | null) | Media;
  painPoints?:
    | {
        title: string;
        severity?: ('low' | 'medium' | 'high') | null;
        id?: string | null;
      }[]
    | null;
  goals?:
    | {
        title: string;
        priority?: ('low' | 'medium' | 'high') | null;
        id?: string | null;
      }[]
    | null;
  experienceLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  budgetRange?: ('free' | 'low' | 'medium' | 'high') | null;
  timeAvailability?: ('minimal' | 'moderate' | 'dedicated') | null;
  /**
   * Display order (lower = first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makers".
 */
export interface Maker {
  id: number;
  title: string;
  /**
   * Short biography
   */
  bio?: string | null;
  /**
   * Full profile description
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * City, Country
   */
  location?: string | null;
  profileImage?: (number | null) | Media;
  backgroundImage?: (number | null) | Media;
  website?: string | null;
  experienceLevel?: ('beginner' | 'intermediate' | 'advanced' | 'expert') | null;
  /**
   * AI tools this maker uses
   */
  toolsExpertise?: (number | Tool)[] | null;
  availability?: ('available' | 'selective' | 'unavailable' | 'open-source-only') | null;
  socialLinks?:
    | {
        platform: 'twitter' | 'instagram' | 'linkedin' | 'github' | 'youtube' | 'dribbble' | 'behance' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  slug: string;
  specialties?: (number | MakerSpecialty)[] | null;
  /**
   * Feature in homepage slider
   */
  featured?: boolean | null;
  /**
   * Position in featured slider (1-10)
   */
  featuredPosition?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maker-specialties".
 */
export interface MakerSpecialty {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  heroBackground?: (number | null) | Media;
  projectYear?: number | null;
  projectAuthor?: string | null;
  /**
   * Live project URL
   */
  projectUrl?: string | null;
  demoUrl?: string | null;
  githubUrl?: string | null;
  /**
   * Describe the creation process
   */
  workflow?: string | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced' | 'expert') | null;
  /**
   * e.g., "2 hours", "3 days"
   */
  timeSpent?: string | null;
  toolsUsed?:
    | {
        name: string;
        category?: string | null;
        url?: string | null;
        /**
         * How this tool was used
         */
        usage?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * For audio/video (e.g., "2:39")
   */
  duration?: string | null;
  genre?: string | null;
  audioFile?: (number | null) | Media;
  videoFile?: (number | null) | Media;
  mediaGallery?: (number | Media)[] | null;
  socialLinks?:
    | {
        platform: 'twitter' | 'instagram' | 'youtube' | 'tiktok' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  slug: string;
  communityType?: (number | null) | CommunityType;
  views?: number | null;
  /**
   * Feature in homepage hero
   */
  featuredInHero?: boolean | null;
  /**
   * Feature in showcase section
   */
  featuredInShowcase?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-types".
 */
export interface CommunityType {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  /**
   * Lucide icon name
   */
  icon?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Brief summary for listings
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  categoryBadge?:
    | ('trending' | 'breaking' | 'new-release' | 'analysis' | 'industry' | 'policy' | 'research' | 'tutorial')
    | null;
  /**
   * Override the default publication date
   */
  publicationDateOverride?: string | null;
  slug: string;
  newsCategory?: (number | null) | NewsCategory;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories".
 */
export interface NewsCategory {
  id: number;
  title: string;
  slug: string;
  /**
   * Badge color (hex)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examples".
 */
export interface Example {
  id: number;
  title: string;
  tagline?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  difficultyLevel?: ('beginner' | 'intermediate' | 'advanced') | null;
  timeToCreate?:
    | ('5-minutes' | '10-minutes' | '30-minutes' | '1-hour' | '2-4-hours' | '1-day' | 'multiple-days')
    | null;
  costRange?: ('free' | 'under-10' | '10-25' | '25-50' | '50-100' | 'over-100') | null;
  creatorInfo?: {
    name?: string | null;
    /**
     * e.g., "AI Artist", "Content Creator"
     */
    title?: string | null;
    website?: string | null;
  };
  toolsUsed?:
    | {
        name: string;
        /**
         * What was this tool used for?
         */
        purpose?: string | null;
        id?: string | null;
      }[]
    | null;
  stepByStep?:
    | {
        stepNumber: number;
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  promptsUsed?:
    | {
        tool: string;
        prompt: string;
        id?: string | null;
      }[]
    | null;
  beforeAfter?: {
    before?: (number | null) | Media;
    after?: (number | null) | Media;
  };
  keyOutcomes?:
    | {
        outcome: string;
        /**
         * e.g., "50% time saved"
         */
        metric?: string | null;
        id?: string | null;
      }[]
    | null;
  lessonsLearned?: string | null;
  downloadFiles?:
    | {
        name: string;
        file?: (number | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  helpfulLinks?:
    | {
        title: string;
        url: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  slug: string;
  creationType?: (number | null) | CreationType;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'makers';
        value: number | Maker;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'examples';
        value: number | Example;
      } | null)
    | ({
        relationTo: 'tool-categories';
        value: number | ToolCategory;
      } | null)
    | ({
        relationTo: 'creation-types';
        value: number | CreationType;
      } | null)
    | ({
        relationTo: 'maker-specialties';
        value: number | MakerSpecialty;
      } | null)
    | ({
        relationTo: 'community-types';
        value: number | CommunityType;
      } | null)
    | ({
        relationTo: 'news-categories';
        value: number | NewsCategory;
      } | null)
    | ({
        relationTo: 'user-situations';
        value: number | UserSituation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  excerpt?: T;
  content?: T;
  logo?: T;
  website?: T;
  pricingModel?: T;
  pricingSummary?: T;
  difficulty?: T;
  useCases?: T;
  platforms?: T;
  keyFeatures?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        users?: T;
        rating?: T;
        company?: T;
        launchYear?: T;
      };
  slug?: T;
  featured?: T;
  toolCategory?: T;
  creationTypes?: T;
  userSituations?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "makers_select".
 */
export interface MakersSelect<T extends boolean = true> {
  title?: T;
  bio?: T;
  content?: T;
  location?: T;
  profileImage?: T;
  backgroundImage?: T;
  website?: T;
  experienceLevel?: T;
  toolsExpertise?: T;
  availability?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  specialties?: T;
  featured?: T;
  featuredPosition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  heroBackground?: T;
  projectYear?: T;
  projectAuthor?: T;
  projectUrl?: T;
  demoUrl?: T;
  githubUrl?: T;
  workflow?: T;
  difficulty?: T;
  timeSpent?: T;
  toolsUsed?:
    | T
    | {
        name?: T;
        category?: T;
        url?: T;
        usage?: T;
        id?: T;
      };
  duration?: T;
  genre?: T;
  audioFile?: T;
  videoFile?: T;
  mediaGallery?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  communityType?: T;
  views?: T;
  featuredInHero?: T;
  featuredInShowcase?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  categoryBadge?: T;
  publicationDateOverride?: T;
  slug?: T;
  newsCategory?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "examples_select".
 */
export interface ExamplesSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  content?: T;
  difficultyLevel?: T;
  timeToCreate?: T;
  costRange?: T;
  creatorInfo?:
    | T
    | {
        name?: T;
        title?: T;
        website?: T;
      };
  toolsUsed?:
    | T
    | {
        name?: T;
        purpose?: T;
        id?: T;
      };
  stepByStep?:
    | T
    | {
        stepNumber?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  promptsUsed?:
    | T
    | {
        tool?: T;
        prompt?: T;
        id?: T;
      };
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
      };
  keyOutcomes?:
    | T
    | {
        outcome?: T;
        metric?: T;
        id?: T;
      };
  lessonsLearned?: T;
  downloadFiles?:
    | T
    | {
        name?: T;
        file?: T;
        description?: T;
        id?: T;
      };
  helpfulLinks?:
    | T
    | {
        title?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  slug?: T;
  creationType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-categories_select".
 */
export interface ToolCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  color?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creation-types_select".
 */
export interface CreationTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  tagline?: T;
  description?: T;
  color?: T;
  gradientColor?: T;
  featuredImage?: T;
  examplePrompts?:
    | T
    | {
        prompt?: T;
        featured?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        toolCount?: T;
        projectCount?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maker-specialties_select".
 */
export interface MakerSpecialtiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-types_select".
 */
export interface CommunityTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-categories_select".
 */
export interface NewsCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-situations_select".
 */
export interface UserSituationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  tagline?: T;
  description?: T;
  color?: T;
  accentColor?: T;
  avatar?: T;
  painPoints?:
    | T
    | {
        title?: T;
        severity?: T;
        id?: T;
      };
  goals?:
    | T
    | {
        title?: T;
        priority?: T;
        id?: T;
      };
  experienceLevel?: T;
  budgetRange?: T;
  timeAvailability?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}