<?php
/**
 * ACF Field Groups Configuration
 * 
 * This file defines all the ACF field groups for the VibeMake project
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

// Register ACF fields programmatically
add_action('acf/init', 'vibemake_register_acf_fields');
function vibemake_register_acf_fields() {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    // Unified Project Fields (combining AI Projects and Community Projects)
    acf_add_local_field_group([
        'key' => 'group_project_fields',
        'title' => 'Project Details',
        'fields' => [
            [
                'key' => 'field_project_year',
                'label' => 'Project Year',
                'name' => 'project_year',
                'type' => 'number',
                'default_value' => date('Y'),
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_author',
                'label' => 'Project Author',
                'name' => 'project_author',
                'type' => 'text',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_workflow',
                'label' => 'Project Workflow',
                'name' => 'project_workflow',
                'type' => 'textarea',
                'instructions' => 'Describe the workflow used to create this project',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_difficulty',
                'label' => 'Project Difficulty',
                'name' => 'project_difficulty',
                'type' => 'select',
                'choices' => [
                    'beginner' => 'Beginner',
                    'intermediate' => 'Intermediate',
                    'advanced' => 'Advanced',
                    'expert' => 'Expert',
                ],
                'default_value' => 'intermediate',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_time_spent',
                'label' => 'Time Spent',
                'name' => 'project_time_spent',
                'type' => 'text',
                'placeholder' => 'e.g., 2 hours, 3 days',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tools_used',
                'label' => 'Tools Used',
                'name' => 'tools_used',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Tool',
                'show_in_graphql' => true,
                'sub_fields' => [
                    [
                        'key' => 'field_tool_name',
                        'label' => 'Tool Name',
                        'name' => 'tool_name',
                        'type' => 'text',
                        'required' => true,
                    ],
                    [
                        'key' => 'field_tool_category',
                        'label' => 'Tool Category',
                        'name' => 'tool_category',
                        'type' => 'select',
                        'choices' => [
                            'ai-model' => 'AI Model',
                            'image-gen' => 'Image Generation',
                            'text-gen' => 'Text Generation',
                            'audio-gen' => 'Audio Generation',
                            'video-gen' => 'Video Generation',
                            'code-gen' => 'Code Generation',
                            'design' => 'Design Tool',
                            'development' => 'Development Tool',
                            'other' => 'Other',
                        ],
                    ],
                    [
                        'key' => 'field_tool_url',
                        'label' => 'Tool URL',
                        'name' => 'tool_url',
                        'type' => 'url',
                    ],
                    [
                        'key' => 'field_tool_usage',
                        'label' => 'How it was used',
                        'name' => 'tool_usage',
                        'type' => 'textarea',
                        'rows' => 2,
                    ],
                ],
            ],
            [
                'key' => 'field_project_url',
                'label' => 'Live Project URL',
                'name' => 'project_url',
                'type' => 'url',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_hero_background',
                'label' => 'Hero Background Image',
                'name' => 'hero_background',
                'type' => 'image',
                'return_format' => 'id',
                'preview_size' => 'medium',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_featured_in_hero',
                'label' => 'Feature in Hero Banner',
                'name' => 'featured_in_hero',
                'type' => 'true_false',
                'instructions' => 'Check this to feature this project in the homepage hero banner. <strong>Note:</strong> Checking this will automatically unfeature any other project that is currently featured.',
                'required' => 0,
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Featured',
                'ui_off_text' => 'Not Featured',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_featured_in_showcase',
                'label' => 'Feature in Showcase Section',
                'name' => 'featured_in_showcase',
                'type' => 'true_false',
                'instructions' => 'Check this to feature this project in the showcase section (above Tools by Category). <strong>Note:</strong> Checking this will automatically unfeature any other project that is currently featured in the showcase.',
                'required' => 0,
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Featured',
                'ui_off_text' => 'Not Featured',
                'show_in_graphql' => true,
            ],
            // Additional fields from Community Projects
            [
                'key' => 'field_project_views',
                'label' => 'View Count',
                'name' => 'project_views',
                'type' => 'number',
                'default_value' => 0,
                'readonly' => true,
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_demo_url',
                'label' => 'Demo URL',
                'name' => 'project_demo_url',
                'type' => 'url',
                'placeholder' => 'https://demo.example.com',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_github_url',
                'label' => 'GitHub Repository',
                'name' => 'project_github_url',
                'type' => 'url',
                'placeholder' => 'https://github.com/username/repo',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_duration',
                'label' => 'Duration (for audio/video)',
                'name' => 'duration',
                'type' => 'text',
                'placeholder' => 'e.g., 2:39',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_genre',
                'label' => 'Genre/Style',
                'name' => 'genre',
                'type' => 'text',
                'placeholder' => 'e.g., Electronic, Abstract',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_audio_file',
                'label' => 'Audio File',
                'name' => 'audio_file',
                'type' => 'file',
                'return_format' => 'id',
                'mime_types' => 'mp3,wav,ogg,m4a',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_video_file',
                'label' => 'Video File',
                'name' => 'video_file',
                'type' => 'file',
                'return_format' => 'id',
                'mime_types' => 'mp4,webm,mov,avi',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_media',
                'label' => 'Additional Media Gallery',
                'name' => 'project_media',
                'type' => 'gallery',
                'return_format' => 'id',
                'preview_size' => 'medium',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_social_links',
                'label' => 'Project Social Links',
                'name' => 'project_social_links',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Social Link',
                'show_in_graphql' => true,
                'sub_fields' => [
                    [
                        'key' => 'field_project_social_platform',
                        'label' => 'Platform',
                        'name' => 'social_platform',
                        'type' => 'text',
                        'required' => true,
                    ],
                    [
                        'key' => 'field_project_social_url',
                        'label' => 'URL',
                        'name' => 'social_url',
                        'type' => 'url',
                        'required' => true,
                    ],
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'community_project',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'show_in_graphql' => true,
    ]);

    // Maker Fields - Complete field group
    acf_add_local_field_group([
        'key' => 'group_maker_fields',
        'title' => 'Maker Details',
        'fields' => [
            [
                'key' => 'field_maker_location',
                'label' => 'Location',
                'name' => 'maker_location',
                'type' => 'text',
                'placeholder' => 'City, Country',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_maker_bio',
                'label' => 'Biography',
                'name' => 'maker_bio',
                'type' => 'textarea',
                'rows' => 5,
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_profile_image',
                'label' => 'Profile Image',
                'name' => 'profile_image',
                'type' => 'image',
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_background_image',
                'label' => 'Background Image',
                'name' => 'background_image',
                'type' => 'image',
                'return_format' => 'id',
                'preview_size' => 'medium',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_maker_website',
                'label' => 'Personal Website',
                'name' => 'maker_website',
                'type' => 'url',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_maker_experience_level',
                'label' => 'Experience Level',
                'name' => 'maker_experience_level',
                'type' => 'select',
                'choices' => [
                    'beginner' => 'Beginner (0-1 years)',
                    'intermediate' => 'Intermediate (1-3 years)',
                    'advanced' => 'Advanced (3-5 years)',
                    'expert' => 'Expert (5+ years)',
                ],
                'default_value' => 'intermediate',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_maker_tools_expertise',
                'label' => 'AI Tools Expertise',
                'name' => 'maker_tools_expertise',
                'type' => 'checkbox',
                'choices' => [
                    'ChatGPT' => 'ChatGPT',
                    'Midjourney' => 'Midjourney',
                    'Stable Diffusion' => 'Stable Diffusion',
                    'DALL-E' => 'DALL-E',
                    'Runway' => 'Runway',
                    'Claude' => 'Claude',
                    'GitHub Copilot' => 'GitHub Copilot',
                    'Hugging Face' => 'Hugging Face',
                    'Other' => 'Other',
                ],
                'layout' => 'vertical',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_maker_availability',
                'label' => 'Availability',
                'name' => 'maker_availability',
                'type' => 'select',
                'choices' => [
                    'available' => 'Available for projects',
                    'selective' => 'Selective collaborations only',
                    'unavailable' => 'Not available currently',
                    'open-source-only' => 'Open source projects only',
                ],
                'default_value' => 'selective',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_social_links',
                'label' => 'Social Links',
                'name' => 'social_links',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Social Link',
                'show_in_graphql' => true,
                'sub_fields' => [
                    [
                        'key' => 'field_social_platform',
                        'label' => 'Platform',
                        'name' => 'social_platform',
                        'type' => 'select',
                        'choices' => [
                            'Twitter' => 'Twitter',
                            'LinkedIn' => 'LinkedIn',
                            'GitHub' => 'GitHub',
                            'Instagram' => 'Instagram',
                            'YouTube' => 'YouTube',
                            'TikTok' => 'TikTok',
                            'Website' => 'Website',
                            'Other' => 'Other',
                        ],
                        'required' => true,
                    ],
                    [
                        'key' => 'field_social_url',
                        'label' => 'URL',
                        'name' => 'social_url',
                        'type' => 'url',
                        'required' => true,
                    ],
                ],
            ],
            [
                'key' => 'field_featured_maker',
                'label' => 'Feature in Homepage Slider',
                'name' => 'featured_maker',
                'type' => 'true_false',
                'instructions' => 'Check this to feature this maker in the homepage slider. <strong>Note:</strong> You must also set a position below.',
                'required' => 0,
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Featured',
                'ui_off_text' => 'Not Featured',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_featured_position',
                'label' => 'Featured Position',
                'name' => 'featured_position',
                'type' => 'number',
                'instructions' => 'Set the position in the homepage slider (1-10). <strong>Note:</strong> Each position must be unique. Setting a position that\'s already taken will automatically adjust other makers\' positions.',
                'required' => 0,
                'min' => 1,
                'max' => 10,
                'step' => 1,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_featured_maker',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
                'show_in_graphql' => true,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'maker',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'show_in_graphql' => true,
    ]);

    // Community Project Fields - DEPRECATED (Merged into unified Project Fields)
    /* Commented out - Fields have been merged into the unified Project Fields group above
    acf_add_local_field_group([
        'key' => 'group_community_project_fields',
        'title' => 'Community Project Details',
        'fields' => [
            [
                'key' => 'field_project_views',
                'label' => 'View Count',
                'name' => 'project_views',
                'type' => 'number',
                'default_value' => 0,
                'readonly' => true,
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_tools',
                'label' => 'Tools/Platform Used',
                'name' => 'project_tools',
                'type' => 'text',
                'placeholder' => 'e.g., Midjourney, ChatGPT',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_duration',
                'label' => 'Duration (for audio/video)',
                'name' => 'duration',
                'type' => 'text',
                'placeholder' => 'e.g., 2:39',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_genre',
                'label' => 'Genre/Style',
                'name' => 'genre',
                'type' => 'text',
                'placeholder' => 'e.g., Electronic, Abstract',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_url',
                'label' => 'Project URL',
                'name' => 'project_url',
                'type' => 'url',
                'placeholder' => 'https://example.com',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_demo_url',
                'label' => 'Demo URL',
                'name' => 'project_demo_url',
                'type' => 'url',
                'placeholder' => 'https://demo.example.com',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_github_url',
                'label' => 'GitHub Repository',
                'name' => 'project_github_url',
                'type' => 'url',
                'placeholder' => 'https://github.com/username/repo',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_audio_file',
                'label' => 'Audio File',
                'name' => 'audio_file',
                'type' => 'file',
                'return_format' => 'id',
                'mime_types' => 'mp3,wav,ogg,m4a',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_video_file',
                'label' => 'Video File',
                'name' => 'video_file',
                'type' => 'file',
                'return_format' => 'id',
                'mime_types' => 'mp4,webm,mov,avi',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_media',
                'label' => 'Additional Media Gallery',
                'name' => 'project_media',
                'type' => 'gallery',
                'return_format' => 'id',
                'preview_size' => 'medium',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_project_social_links',
                'label' => 'Project Social Links',
                'name' => 'project_social_links',
                'type' => 'repeater',
                'layout' => 'table',
                'button_label' => 'Add Social Link',
                'show_in_graphql' => true,
                'sub_fields' => [
                    [
                        'key' => 'field_project_social_platform',
                        'label' => 'Platform',
                        'name' => 'social_platform',
                        'type' => 'text',
                        'required' => true,
                    ],
                    [
                        'key' => 'field_project_social_url',
                        'label' => 'URL',
                        'name' => 'social_url',
                        'type' => 'url',
                        'required' => true,
                    ],
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'community_project',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'show_in_graphql' => true,
    ]);
    */

    // News Article Fields (for posts) - Complete field group
    acf_add_local_field_group([
        'key' => 'group_news_fields',
        'title' => 'News Article Details',
        'fields' => [
            [
                'key' => 'field_article_category_badge',
                'label' => 'Category Badge',
                'name' => 'article_category_badge',
                'type' => 'select',
                'choices' => [
                    'TRENDING' => 'TRENDING',
                    'BREAKING' => 'BREAKING',
                    'NEW RELEASE' => 'NEW RELEASE',
                    'ANALYSIS' => 'ANALYSIS',
                    'INDUSTRY' => 'INDUSTRY',
                    'POLICY' => 'POLICY',
                    'RESEARCH' => 'RESEARCH',
                    'TUTORIAL' => 'TUTORIAL',
                ],
                'allow_null' => true,
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_publication_date_override',
                'label' => 'Publication Date Override',
                'name' => 'publication_date_override',
                'type' => 'date_picker',
                'display_format' => 'F j, Y',
                'return_format' => 'Y-m-d',
                'instructions' => 'Leave empty to use post publish date',
                'show_in_graphql' => true,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'show_in_graphql' => true,
    ]);

    // ✨ AI Tools Field Group - Modern Enhanced UI
    acf_add_local_field_group([
        'key' => 'group_ai_tool_details_modern',
        'title' => '🤖 AI Tool Information',
        'fields' => [
            // ℹ️ BASIC INFORMATION TAB
            [
                'key' => 'field_basic_info_tab',
                'label' => 'ℹ️ Basic Information',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_tool_tagline_modern',
                'label' => '💭 Tool Tagline',
                'name' => 'tool_tagline',
                'type' => 'text',
                'instructions' => 'Create a memorable one-liner that captures what makes this tool special',
                'required' => 1,
                'placeholder' => 'e.g., "The AI that writes like you" or "Turn ideas into stunning visuals"',
                'maxlength' => 120,
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tool_website_modern',
                'label' => '🌐 Official Website',
                'name' => 'tool_website',
                'type' => 'url',
                'instructions' => 'The main website where users can access this tool',
                'required' => 1,
                'placeholder' => 'https://example.com',
                'wrapper' => ['width' => '50'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tool_featured_modern',
                'label' => '⭐ Featured Tool',
                'name' => 'tool_featured',
                'type' => 'true_false',
                'instructions' => 'Mark as featured to highlight in discovery listings',
                'ui' => 1,
                'ui_on_text' => '⭐ Featured',
                'ui_off_text' => 'Standard',
                'default_value' => 0,
                'wrapper' => ['width' => '50'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tool_logo_modern',
                'label' => '🎨 Tool Logo',
                'name' => 'tool_logo',
                'type' => 'image',
                'instructions' => 'Upload a high-quality square logo (minimum 200x200px). This will be used in tool cards and listings.',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => 200,
                'min_height' => 200,
                'show_in_graphql' => true,
            ],
            
            // 🚀 CAPABILITIES TAB
            [
                'key' => 'field_capabilities_tab_modern',
                'label' => '🚀 Capabilities',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
            ],
            [
                'key' => 'field_tool_use_cases_modern',
                'label' => '🎯 What Can Users Create?',
                'name' => 'tool_use_cases',
                'type' => 'checkbox',
                'instructions' => 'Select all the types of content users can create with this tool',
                'choices' => [
                    'writing' => '✍️ Writing & Text Content',
                    'images' => '🎨 Images & Visual Art',
                    'video' => '🎬 Video Content',
                    'audio' => '🎵 Audio & Music',
                    'code' => '💻 Code & Development',
                    'design' => '🎨 Design & UI/UX',
                    'data' => '📊 Data Analysis',
                    'automation' => '⚙️ Automation & Workflows',
                    'education' => '📚 Learning & Education',
                    'business' => '💼 Business & Marketing',
                ],
                'layout' => 'vertical',
                'return_format' => 'value',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tool_difficulty_modern',
                'label' => '📊 Difficulty Level',
                'name' => 'tool_difficulty',
                'type' => 'button_group',
                'instructions' => 'How technical is this tool to use?',
                'choices' => [
                    'beginner' => '🟢 Beginner Friendly',
                    'intermediate' => '🟡 Some Experience Needed',
                    'advanced' => '🔴 Technical Expertise Required',
                ],
                'default_value' => 'beginner',
                'layout' => 'horizontal',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tool_key_features_modern',
                'label' => '✨ Key Features',
                'name' => 'tool_key_features',
                'type' => 'repeater',
                'instructions' => 'Highlight the standout features that make this tool special',
                'min' => 1,
                'max' => 6,
                'layout' => 'block',
                'button_label' => '➕ Add Feature',
                'sub_fields' => [
                    [
                        'key' => 'field_feature_icon_modern',
                        'label' => 'Icon',
                        'name' => 'feature_icon',
                        'type' => 'select',
                        'choices' => [
                            '✨' => '✨ Magic/AI',
                            '🚀' => '🚀 Speed/Performance',
                            '💡' => '💡 Innovation',
                            '🎯' => '🎯 Precision/Accuracy',
                            '⚡' => '⚡ Fast/Instant',
                            '🔧' => '🔧 Customization',
                            '🎨' => '🎨 Creative/Design',
                            '📊' => '📊 Analytics/Data',
                            '🔒' => '🔒 Security/Privacy',
                            '🌟' => '🌟 Premium/Quality',
                            '🔥' => '🔥 Popular/Trending',
                            '💎' => '💎 Professional/Enterprise',
                        ],
                        'default_value' => '✨',
                        'wrapper' => ['width' => '15'],
                    ],
                    [
                        'key' => 'field_feature_title_modern',
                        'label' => 'Feature Name',
                        'name' => 'feature_title',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "Real-time Collaboration"',
                        'wrapper' => ['width' => '35'],
                    ],
                    [
                        'key' => 'field_feature_description_modern',
                        'label' => 'Description',
                        'name' => 'feature_description',
                        'type' => 'textarea',
                        'rows' => 2,
                        'placeholder' => 'Explain what makes this feature valuable...',
                        'wrapper' => ['width' => '50'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            
            // 💰 PRICING TAB
            [
                'key' => 'field_pricing_tab_modern',
                'label' => '💰 Pricing',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
            ],
            [
                'key' => 'field_tool_pricing_model_modern',
                'label' => '💳 Pricing Model',
                'name' => 'tool_pricing_model',
                'type' => 'button_group',
                'instructions' => 'What is the primary pricing structure?',
                'choices' => [
                    'free' => '🆓 Completely Free',
                    'freemium' => '🎯 Freemium (Free + Paid)',
                    'paid' => '💰 Paid Only',
                    'custom' => '📞 Custom/Enterprise',
                ],
                'default_value' => 'freemium',
                'layout' => 'horizontal',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tool_pricing_summary_modern',
                'label' => '📋 Pricing Summary',
                'name' => 'tool_pricing_summary',
                'type' => 'text',
                'instructions' => 'Quick overview of pricing options (will be displayed on tool cards)',
                'placeholder' => 'e.g., "Free plan available, Pro from $20/month"',
                'show_in_graphql' => true,
            ],
            
            // 📈 STATS & DETAILS TAB
            [
                'key' => 'field_stats_tab_modern',
                'label' => '📈 Stats & Details',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
            ],
            [
                'key' => 'field_tool_stats_modern',
                'label' => '📊 Tool Statistics',
                'name' => 'tool_stats',
                'type' => 'group',
                'instructions' => 'Add credibility with real numbers and facts',
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_stat_users_modern',
                        'label' => '👥 Active Users',
                        'name' => 'stat_users',
                        'type' => 'text',
                        'placeholder' => 'e.g., "10M+" or "500K+"',
                        'prepend' => '👥',
                        'wrapper' => ['width' => '25'],
                    ],
                    [
                        'key' => 'field_stat_rating_modern',
                        'label' => '⭐ User Rating',
                        'name' => 'stat_rating',
                        'type' => 'number',
                        'min' => 0,
                        'max' => 5,
                        'step' => 0.1,
                        'placeholder' => '4.8',
                        'prepend' => '⭐',
                        'wrapper' => ['width' => '25'],
                    ],
                    [
                        'key' => 'field_stat_company_modern',
                        'label' => '🏢 Company',
                        'name' => 'stat_company',
                        'type' => 'text',
                        'placeholder' => 'e.g., "OpenAI", "Google"',
                        'prepend' => '🏢',
                        'wrapper' => ['width' => '25'],
                    ],
                    [
                        'key' => 'field_stat_year_modern',
                        'label' => '📅 Launch Year',
                        'name' => 'stat_year',
                        'type' => 'number',
                        'min' => 2000,
                        'max' => 2030,
                        'default_value' => date('Y'),
                        'prepend' => '📅',
                        'wrapper' => ['width' => '25'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_tool_platforms_modern',
                'label' => '💻 Available Platforms',
                'name' => 'tool_platforms',
                'type' => 'checkbox',
                'instructions' => 'Where can users access this tool?',
                'choices' => [
                    'web' => '🌐 Web Browser',
                    'ios' => '📱 iOS App',
                    'android' => '🤖 Android App',
                    'mac' => '💻 Mac App',
                    'windows' => '🖥️ Windows App',
                    'api' => '🔌 API Access',
                    'plugin' => '🧩 Plugin/Extension',
                ],
                'layout' => 'horizontal',
                'return_format' => 'value',
                'show_in_graphql' => true,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'tool',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
        'show_in_graphql' => true,
        'graphql_field_name' => 'toolFields',
    ]);

    // 🎨 Creation Types Taxonomy - Enhanced UI
    acf_add_local_field_group([
        'key' => 'group_creation_type_meta',
        'title' => '🎨 Creation Type Details',
        'fields' => [
            [
                'key' => 'field_creation_type_icon',
                'label' => '🎭 Icon',
                'name' => 'creation_type_icon',
                'type' => 'select',
                'instructions' => 'Choose an emoji that represents this creation type',
                'choices' => [
                    '✍️' => '✍️ Writing & Text',
                    '🎨' => '🎨 Images & Art', 
                    '🎬' => '🎬 Video & Film',
                    '🎵' => '🎵 Audio & Music',
                    '💻' => '💻 Code & Development',
                    '🎪' => '🎪 Design & UI/UX',
                    '📊' => '📊 Data & Analytics',
                    '⚙️' => '⚙️ Automation & Tools',
                    '📚' => '📚 Education & Learning',
                    '💼' => '💼 Business & Marketing',
                    '🔬' => '🔬 Research & Science',
                    '🎮' => '🎮 Games & Entertainment',
                    '🏠' => '🏠 Productivity & Life',
                    '🌐' => '🌐 Web & Digital',
                    '📱' => '📱 Mobile & Apps',
                ],
                'default_value' => '🎨',
                'wrapper' => ['width' => '30'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_creation_type_color',
                'label' => '🎨 Brand Color',
                'name' => 'creation_type_color',
                'type' => 'color_picker',
                'instructions' => 'Primary color for this creation type (used in cards, buttons, etc.)',
                'default_value' => '#6366f1',
                'wrapper' => ['width' => '35'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_creation_type_gradient',
                'label' => '🌈 Gradient Color',
                'name' => 'creation_type_gradient',
                'type' => 'color_picker',
                'instructions' => 'Secondary color for gradients and hover effects',
                'default_value' => '#8b5cf6',
                'wrapper' => ['width' => '35'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_creation_type_tagline',
                'label' => '💭 Tagline',
                'name' => 'creation_type_tagline',
                'type' => 'text',
                'instructions' => 'Short inspirational phrase about this creation type',
                'placeholder' => 'e.g., "Bring your words to life" or "Turn imagination into visuals"',
                'maxlength' => 80,
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_creation_type_description',
                'label' => '📝 Description',
                'name' => 'creation_type_description',
                'type' => 'textarea',
                'instructions' => 'Detailed description of what users can create in this category',
                'rows' => 4,
                'placeholder' => 'Describe the amazing things users can create with AI tools in this category...',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_creation_type_featured_image',
                'label' => '🖼️ Featured Image',
                'name' => 'creation_type_featured_image',
                'type' => 'image',
                'instructions' => 'Hero image for this creation type (used in category pages and cards)',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_creation_type_examples',
                'label' => '💡 Example Prompts',
                'name' => 'creation_type_examples',
                'type' => 'repeater',
                'instructions' => 'Add example search prompts users might type for this creation type',
                'min' => 3,
                'max' => 8,
                'layout' => 'block',
                'button_label' => '➕ Add Example',
                'sub_fields' => [
                    [
                        'key' => 'field_example_prompt',
                        'label' => 'Example Prompt',
                        'name' => 'example_prompt',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "I want to create a logo for my startup"',
                        'wrapper' => ['width' => '70'],
                    ],
                    [
                        'key' => 'field_example_featured',
                        'label' => 'Featured?',
                        'name' => 'example_featured',
                        'type' => 'true_false',
                        'instructions' => 'Show in homepage suggestions',
                        'ui' => 1,
                        'ui_on_text' => 'Featured',
                        'ui_off_text' => 'Normal',
                        'wrapper' => ['width' => '30'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_creation_type_stats',
                'label' => '📊 Category Statistics',
                'name' => 'creation_type_stats',
                'type' => 'group',
                'instructions' => 'Add engaging stats about this creation type',
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_stat_tools_count',
                        'label' => '🔧 Tools Available',
                        'name' => 'stat_tools_count',
                        'type' => 'text',
                        'placeholder' => 'e.g., "50+ tools"',
                        'prepend' => '🔧',
                        'wrapper' => ['width' => '33'],
                    ],
                    [
                        'key' => 'field_stat_difficulty',
                        'label' => '📊 Avg Difficulty',
                        'name' => 'stat_difficulty',
                        'type' => 'select',
                        'choices' => [
                            'beginner' => '🟢 Beginner Friendly',
                            'intermediate' => '🟡 Some Learning Required',
                            'advanced' => '🔴 Advanced Skills Needed',
                        ],
                        'default_value' => 'beginner',
                        'wrapper' => ['width' => '33'],
                    ],
                    [
                        'key' => 'field_stat_popularity',
                        'label' => '🔥 Popularity Score',
                        'name' => 'stat_popularity',
                        'type' => 'range',
                        'min' => 1,
                        'max' => 10,
                        'step' => 1,
                        'default_value' => 5,
                        'prepend' => '🔥',
                        'wrapper' => ['width' => '34'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'creation_type',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
        'show_in_graphql' => true,
    ]);

    // 👥 User Situations Taxonomy - Enhanced UI
    acf_add_local_field_group([
        'key' => 'group_user_situation_meta',
        'title' => '👥 User Situation Details',
        'fields' => [
            [
                'key' => 'field_user_situation_icon',
                'label' => '👤 Persona Icon',
                'name' => 'user_situation_icon',
                'type' => 'select',
                'instructions' => 'Choose an emoji that represents this user type',
                'choices' => [
                    '🎓' => '🎓 Student & Learner',
                    '💼' => '💼 Business Professional',
                    '🎨' => '🎨 Creative & Artist',
                    '💻' => '💻 Developer & Tech',
                    '📈' => '📈 Marketer & Growth',
                    '👩‍🏫' => '👩‍🏫 Educator & Teacher',
                    '🚀' => '🚀 Entrepreneur & Founder',
                    '📊' => '📊 Analyst & Data Scientist',
                    '✍️' => '✍️ Writer & Journalist',
                    '📱' => '📱 Content Creator & Influencer',
                    '🔬' => '🔬 Researcher & Academic',
                    '🏥' => '🏥 Healthcare Professional',
                    '⚖️' => '⚖️ Legal Professional',
                    '🎯' => '🎯 Freelancer & Consultant',
                    '🏠' => '🏠 Personal & Lifestyle',
                ],
                'default_value' => '🎓',
                'wrapper' => ['width' => '30'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_color',
                'label' => '🎨 Theme Color',
                'name' => 'user_situation_color',
                'type' => 'color_picker',
                'instructions' => 'Primary color for this user situation (used in persona cards, filters, etc.)',
                'default_value' => '#3b82f6',
                'wrapper' => ['width' => '35'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_accent',
                'label' => '✨ Accent Color',
                'name' => 'user_situation_accent',
                'type' => 'color_picker',
                'instructions' => 'Secondary color for highlights and gradients',
                'default_value' => '#1d4ed8',
                'wrapper' => ['width' => '35'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_tagline',
                'label' => '💭 Persona Tagline',
                'name' => 'user_situation_tagline',
                'type' => 'text',
                'instructions' => 'Motivational phrase that speaks to this user type',
                'placeholder' => 'e.g., "Learn faster with AI" or "Scale your business intelligently"',
                'maxlength' => 60,
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_description',
                'label' => '📝 Persona Description',
                'name' => 'user_situation_description',
                'type' => 'textarea',
                'instructions' => 'Describe this user type and their typical AI needs',
                'rows' => 4,
                'placeholder' => 'What challenges does this persona face? How can AI help them succeed?',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_avatar',
                'label' => '🖼️ Persona Avatar',
                'name' => 'user_situation_avatar',
                'type' => 'image',
                'instructions' => 'Representative image for this user type (illustrations work best)',
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_pain_points',
                'label' => '😰 Common Pain Points',
                'name' => 'user_situation_pain_points',
                'type' => 'repeater',
                'instructions' => 'What challenges does this user type typically face?',
                'min' => 2,
                'max' => 6,
                'layout' => 'block',
                'button_label' => '➕ Add Pain Point',
                'sub_fields' => [
                    [
                        'key' => 'field_pain_point_title',
                        'label' => 'Challenge',
                        'name' => 'pain_point_title',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "Limited time for content creation"',
                        'wrapper' => ['width' => '60'],
                    ],
                    [
                        'key' => 'field_pain_point_severity',
                        'label' => 'Severity',
                        'name' => 'pain_point_severity',
                        'type' => 'select',
                        'choices' => [
                            'low' => '🟢 Minor Issue',
                            'medium' => '🟡 Moderate Challenge',
                            'high' => '🔴 Major Pain Point',
                        ],
                        'default_value' => 'medium',
                        'wrapper' => ['width' => '40'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_goals',
                'label' => '🎯 Typical Goals',
                'name' => 'user_situation_goals',
                'type' => 'repeater',
                'instructions' => 'What does this user type want to achieve with AI?',
                'min' => 2,
                'max' => 6,
                'layout' => 'block',
                'button_label' => '➕ Add Goal',
                'sub_fields' => [
                    [
                        'key' => 'field_goal_title',
                        'label' => 'Goal',
                        'name' => 'goal_title',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "Create professional presentations quickly"',
                        'wrapper' => ['width' => '60'],
                    ],
                    [
                        'key' => 'field_goal_priority',
                        'label' => 'Priority',
                        'name' => 'goal_priority',
                        'type' => 'select',
                        'choices' => [
                            'low' => '🟢 Nice to Have',
                            'medium' => '🟡 Important',
                            'high' => '🔴 Critical Need',
                        ],
                        'default_value' => 'medium',
                        'wrapper' => ['width' => '40'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_user_situation_personas',
                'label' => '📊 Persona Statistics',
                'name' => 'user_situation_personas',
                'type' => 'group',
                'instructions' => 'Add relevant stats about this user type',
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_persona_experience_level',
                        'label' => '💡 Typical AI Experience',
                        'name' => 'persona_experience_level',
                        'type' => 'select',
                        'choices' => [
                            'beginner' => '🟢 New to AI',
                            'intermediate' => '🟡 Some AI Experience',
                            'advanced' => '🔴 AI Power User',
                        ],
                        'default_value' => 'beginner',
                        'wrapper' => ['width' => '33'],
                    ],
                    [
                        'key' => 'field_persona_budget_range',
                        'label' => '💰 Budget Range',
                        'name' => 'persona_budget_range',
                        'type' => 'select',
                        'choices' => [
                            'free' => '🆓 Free Tools Only',
                            'low' => '💰 $0-50/month',
                            'medium' => '💰💰 $50-200/month',
                            'high' => '💰💰💰 $200+/month',
                        ],
                        'default_value' => 'low',
                        'wrapper' => ['width' => '33'],
                    ],
                    [
                        'key' => 'field_persona_time_availability',
                        'label' => '⏰ Time to Learn',
                        'name' => 'persona_time_availability',
                        'type' => 'select',
                        'choices' => [
                            'minimal' => '⚡ Want Quick Results',
                            'moderate' => '🕐 Can Spend Some Time',
                            'extensive' => '📚 Love to Deep Dive',
                        ],
                        'default_value' => 'minimal',
                        'wrapper' => ['width' => '34'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'user_situation',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
        'show_in_graphql' => true,
    ]);
}

// Register GraphQL fields for ACF
add_action('graphql_register_types', 'vibemake_register_acf_graphql_fields');
function vibemake_register_acf_graphql_fields() {
    // Ensure ACF fields are exposed in GraphQL
    if (function_exists('register_graphql_field')) {
        // Add acfNewsFields to Post type
        register_graphql_field('Post', 'acfNewsFields', [
            'type' => 'NewsFields',
            'description' => 'ACF fields for news articles',
            'resolve' => function($post) {
                return [
                    'articleCategoryBadge' => get_field('article_category_badge', $post->ID),
                    'publicationDateOverride' => get_field('publication_date_override', $post->ID),
                ];
            }
        ]);

        // Register NewsFields type
        register_graphql_object_type('NewsFields', [
            'description' => 'ACF fields for news articles',
            'fields' => [
                'articleCategoryBadge' => ['type' => 'String'],
                'publicationDateOverride' => ['type' => 'String'],
            ],
        ]);

        // Add featured fields to Maker type
        register_graphql_field('Maker', 'featuredMaker', [
            'type' => 'Boolean',
            'description' => 'Whether this maker is featured in the homepage slider',
            'resolve' => function($maker) {
                return (bool) get_field('featured_maker', $maker->ID);
            }
        ]);

        register_graphql_field('Maker', 'featuredPosition', [
            'type' => 'Int',
            'description' => 'Position of this maker in the homepage slider (1-10)',
            'resolve' => function($maker) {
                return (int) get_field('featured_position', $maker->ID);
            }
        ]);

        // Add image fields to Maker type
        register_graphql_field('Maker', 'profileImage', [
            'type' => 'MediaItem',
            'description' => 'Profile image of the maker',
            'resolve' => function($maker, $args, $context, $info) {
                $image_id = get_field('profile_image', $maker->ID);
                if (!$image_id) {
                    return null;
                }
                return $context->get_loader('post')->load_deferred($image_id);
            }
        ]);

        register_graphql_field('Maker', 'backgroundImage', [
            'type' => 'MediaItem',
            'description' => 'Background image for the maker profile',
            'resolve' => function($maker, $args, $context, $info) {
                $image_id = get_field('background_image', $maker->ID);
                if (!$image_id) {
                    return null;
                }
                return $context->get_loader('post')->load_deferred($image_id);
            }
        ]);

        // Add other Maker fields
        register_graphql_field('Maker', 'makerLocation', [
            'type' => 'String',
            'description' => 'Location of the maker',
            'resolve' => function($maker) {
                return get_field('maker_location', $maker->ID);
            }
        ]);

        register_graphql_field('Maker', 'makerBio', [
            'type' => 'String',
            'description' => 'Biography of the maker',
            'resolve' => function($maker) {
                return get_field('maker_bio', $maker->ID);
            }
        ]);

        // Add featured fields to CommunityProject type
        register_graphql_field('CommunityProject', 'featuredInHero', [
            'type' => 'Boolean',
            'description' => 'Whether this project is featured in the hero banner',
            'resolve' => function($project) {
                return (bool) get_field('featured_in_hero', $project->ID);
            }
        ]);

        register_graphql_field('CommunityProject', 'featuredInShowcase', [
            'type' => 'Boolean',
            'description' => 'Whether this project is featured in the showcase section',
            'resolve' => function($project) {
                return (bool) get_field('featured_in_showcase', $project->ID);
            }
        ]);
    }

    // ✨ Examples/Templates Field Group - Showcase Real AI Creations
    acf_add_local_field_group([
        'key' => 'group_examples_fields',
        'title' => '💡 Example Details',
        'fields' => [
            // ℹ️ BASIC INFORMATION TAB
            [
                'key' => 'field_example_basic_tab',
                'label' => 'ℹ️ Basic Information',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_example_tagline',
                'label' => '✨ Tagline',
                'name' => 'example_tagline',
                'type' => 'text',
                'instructions' => 'A compelling one-liner that describes this example',
                'placeholder' => 'e.g., "AI-generated logo design for startup in 10 minutes"',
                'maxlength' => 120,
                'required' => 1,
                'wrapper' => ['width' => '70'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_difficulty_level',
                'label' => '📊 Difficulty',
                'name' => 'example_difficulty_level',
                'type' => 'button_group',
                'choices' => [
                    'beginner' => '🟢 Beginner',
                    'intermediate' => '🟡 Intermediate', 
                    'advanced' => '🔴 Advanced',
                ],
                'default_value' => 'beginner',
                'wrapper' => ['width' => '30'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_time_to_create',
                'label' => '⏱️ Time to Create',
                'name' => 'example_time_to_create',
                'type' => 'select',
                'choices' => [
                    '5-minutes' => '⚡ 5 minutes or less',
                    '10-minutes' => '🚀 10-15 minutes',
                    '30-minutes' => '⏰ 30 minutes',
                    '1-hour' => '🕐 1 hour',
                    '2-hours' => '🕑 2-3 hours',
                    'half-day' => '📅 Half day',
                    'full-day' => '📆 Full day',
                    'multiple-days' => '📊 Multiple days',
                ],
                'default_value' => '10-minutes',
                'wrapper' => ['width' => '50'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_cost_range',
                'label' => '💰 Cost Range',
                'name' => 'example_cost_range',
                'type' => 'select',
                'choices' => [
                    'free' => '🆓 Completely Free',
                    'under-10' => '💵 Under $10',
                    '10-25' => '💴 $10-25',
                    '25-50' => '💶 $25-50',
                    '50-100' => '💷 $50-100',
                    'over-100' => '💸 Over $100',
                ],
                'default_value' => 'free',
                'wrapper' => ['width' => '50'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_creator_info',
                'label' => '👤 Creator Information',
                'name' => 'example_creator_info',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_creator_name',
                        'label' => 'Creator Name',
                        'name' => 'creator_name',
                        'type' => 'text',
                        'placeholder' => 'e.g., Sarah Chen',
                        'wrapper' => ['width' => '50'],
                    ],
                    [
                        'key' => 'field_creator_title',
                        'label' => 'Creator Title/Role',
                        'name' => 'creator_title',
                        'type' => 'text',
                        'placeholder' => 'e.g., Freelance Designer, Marketing Manager',
                        'wrapper' => ['width' => '50'],
                    ],
                    [
                        'key' => 'field_creator_website',
                        'label' => 'Creator Website/Portfolio',
                        'name' => 'creator_website',
                        'type' => 'url',
                        'placeholder' => 'https://sarahchen.design',
                    ],
                ],
                'show_in_graphql' => true,
            ],

            // 🛠️ TOOLS & PROCESS TAB
            [
                'key' => 'field_example_tools_tab',
                'label' => '🛠️ Tools & Process',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_example_tools_used',
                'label' => '🔧 AI Tools Used',
                'name' => 'example_tools_used',
                'type' => 'repeater',
                'instructions' => 'List the AI tools that were used to create this example',
                'min' => 1,
                'max' => 5,
                'layout' => 'block',
                'button_label' => '➕ Add Tool',
                'sub_fields' => [
                    [
                        'key' => 'field_tool_name_example',
                        'label' => 'Tool Name',
                        'name' => 'tool_name',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., ChatGPT, Midjourney, RunwayML',
                        'wrapper' => ['width' => '40'],
                    ],
                    [
                        'key' => 'field_tool_purpose_example',
                        'label' => 'What it was used for',
                        'name' => 'tool_purpose',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "Generate initial logo concepts"',
                        'wrapper' => ['width' => '60'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_step_by_step',
                'label' => '📋 Step-by-Step Process',
                'name' => 'example_step_by_step',
                'type' => 'repeater',
                'instructions' => 'Break down the creation process into clear steps',
                'min' => 3,
                'max' => 10,
                'layout' => 'block',
                'button_label' => '➕ Add Step',
                'sub_fields' => [
                    [
                        'key' => 'field_step_number',
                        'label' => 'Step',
                        'name' => 'step_number',
                        'type' => 'number',
                        'required' => 1,
                        'default_value' => 1,
                        'min' => 1,
                        'max' => 20,
                        'wrapper' => ['width' => '15'],
                    ],
                    [
                        'key' => 'field_step_title',
                        'label' => 'Step Title',
                        'name' => 'step_title',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "Define brand personality"',
                        'wrapper' => ['width' => '35'],
                    ],
                    [
                        'key' => 'field_step_description',
                        'label' => 'Description',
                        'name' => 'step_description',
                        'type' => 'textarea',
                        'required' => 1,
                        'rows' => 2,
                        'placeholder' => 'Describe what exactly happens in this step...',
                        'wrapper' => ['width' => '50'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_prompts_used',
                'label' => '💬 Key Prompts Used',
                'name' => 'example_prompts_used',
                'type' => 'repeater',
                'instructions' => 'Share the actual prompts that worked well for this example',
                'min' => 1,
                'max' => 5,
                'layout' => 'block',
                'button_label' => '➕ Add Prompt',
                'sub_fields' => [
                    [
                        'key' => 'field_prompt_tool',
                        'label' => 'Tool Used',
                        'name' => 'prompt_tool',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., ChatGPT, Midjourney',
                        'wrapper' => ['width' => '30'],
                    ],
                    [
                        'key' => 'field_prompt_text',
                        'label' => 'Prompt Text',
                        'name' => 'prompt_text',
                        'type' => 'textarea',
                        'required' => 1,
                        'rows' => 3,
                        'placeholder' => 'Paste the exact prompt that was used...',
                        'wrapper' => ['width' => '70'],
                    ],
                ],
                'show_in_graphql' => true,
            ],

            // 📈 RESULTS & IMPACT TAB
            [
                'key' => 'field_example_results_tab',
                'label' => '📈 Results & Impact',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_example_before_after',
                'label' => '📊 Before vs After',
                'name' => 'example_before_after',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_before_image',
                        'label' => '📷 Before Image (Optional)',
                        'name' => 'before_image',
                        'type' => 'image',
                        'instructions' => 'Show what you started with (if applicable)',
                        'return_format' => 'array',
                        'wrapper' => ['width' => '50'],
                    ],
                    [
                        'key' => 'field_after_image',
                        'label' => '✨ After Image',
                        'name' => 'after_image',
                        'type' => 'image',
                        'instructions' => 'Show the final result',
                        'return_format' => 'array',
                        'required' => 1,
                        'wrapper' => ['width' => '50'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_key_outcomes',
                'label' => '🎯 Key Outcomes',
                'name' => 'example_key_outcomes',
                'type' => 'repeater',
                'instructions' => 'What concrete results did this project achieve?',
                'min' => 2,
                'max' => 6,
                'layout' => 'block',
                'button_label' => '➕ Add Outcome',
                'sub_fields' => [
                    [
                        'key' => 'field_outcome_title',
                        'label' => 'Outcome',
                        'name' => 'outcome_title',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "Saved 5 hours of design time"',
                        'wrapper' => ['width' => '60'],
                    ],
                    [
                        'key' => 'field_outcome_metric',
                        'label' => 'Metric/Value',
                        'name' => 'outcome_metric',
                        'type' => 'text',
                        'placeholder' => 'e.g., "5 hours", "$200 savings", "50% faster"',
                        'wrapper' => ['width' => '40'],
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_lessons_learned',
                'label' => '💡 Lessons Learned',
                'name' => 'example_lessons_learned',
                'type' => 'textarea',
                'instructions' => 'What insights or tips would you share with others trying this?',
                'rows' => 4,
                'placeholder' => 'Share the key insights, gotchas, or tips that would help others succeed with a similar project...',
                'show_in_graphql' => true,
            ],

            // 🔗 RESOURCES TAB
            [
                'key' => 'field_example_resources_tab',
                'label' => '🔗 Resources',
                'name' => '',
                'type' => 'tab',
                'placement' => 'left',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_example_download_files',
                'label' => '📁 Downloadable Files',
                'name' => 'example_download_files',
                'type' => 'repeater',
                'instructions' => 'Provide templates, prompts, or files others can use',
                'max' => 5,
                'layout' => 'table',
                'button_label' => '➕ Add File',
                'sub_fields' => [
                    [
                        'key' => 'field_download_name',
                        'label' => 'File Name',
                        'name' => 'download_name',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "Prompt Template.txt"',
                    ],
                    [
                        'key' => 'field_download_file',
                        'label' => 'File',
                        'name' => 'download_file',
                        'type' => 'file',
                        'required' => 1,
                        'return_format' => 'array',
                    ],
                    [
                        'key' => 'field_download_description',
                        'label' => 'Description',
                        'name' => 'download_description',
                        'type' => 'text',
                        'placeholder' => 'What is this file and how to use it',
                    ],
                ],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_example_helpful_links',
                'label' => '🌐 Helpful Links',
                'name' => 'example_helpful_links',
                'type' => 'repeater',
                'instructions' => 'Share relevant tutorials, tools, or resources',
                'max' => 5,
                'layout' => 'table',
                'button_label' => '➕ Add Link',
                'sub_fields' => [
                    [
                        'key' => 'field_link_title',
                        'label' => 'Link Title',
                        'name' => 'link_title',
                        'type' => 'text',
                        'required' => 1,
                        'placeholder' => 'e.g., "ChatGPT Prompt Writing Guide"',
                    ],
                    [
                        'key' => 'field_link_url',
                        'label' => 'URL',
                        'name' => 'link_url',
                        'type' => 'url',
                        'required' => 1,
                    ],
                    [
                        'key' => 'field_link_description',
                        'label' => 'Description',
                        'name' => 'link_description',
                        'type' => 'text',
                        'placeholder' => 'Why is this link helpful?',
                    ],
                ],
                'show_in_graphql' => true,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'example',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'show_in_graphql' => true,
    ]);

    // Example Difficulty Taxonomy Fields
    acf_add_local_field_group([
        'key' => 'group_example_difficulty_fields',
        'title' => '📊 Difficulty Level Details',
        'fields' => [
            [
                'key' => 'field_difficulty_icon',
                'label' => '🎯 Icon',
                'name' => 'difficulty_icon',
                'type' => 'text',
                'instructions' => 'Emoji or icon to represent this difficulty level',
                'placeholder' => '🟢',
                'maxlength' => 5,
                'wrapper' => ['width' => '20'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_difficulty_color',
                'label' => '🎨 Primary Color',
                'name' => 'difficulty_color',
                'type' => 'color_picker',
                'instructions' => 'Main color for this difficulty level',
                'default_value' => '#3b82f6',
                'wrapper' => ['width' => '40'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_difficulty_description',
                'label' => '📝 Description',
                'name' => 'difficulty_description',
                'type' => 'textarea',
                'instructions' => 'Describe what this difficulty level means',
                'rows' => 2,
                'placeholder' => 'e.g., "Perfect for first-time users with no AI experience"',
                'wrapper' => ['width' => '40'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_difficulty_time_estimate',
                'label' => '⏱️ Typical Time Range',
                'name' => 'difficulty_time_estimate',
                'type' => 'text',
                'instructions' => 'How long do projects of this difficulty usually take?',
                'placeholder' => 'e.g., "5-30 minutes"',
                'wrapper' => ['width' => '50'],
                'show_in_graphql' => true,
            ],
            [
                'key' => 'field_difficulty_prerequisites',
                'label' => '📚 Prerequisites',
                'name' => 'difficulty_prerequisites',
                'type' => 'textarea',
                'instructions' => 'What should users know before attempting this difficulty level?',
                'rows' => 2,
                'placeholder' => 'e.g., "Basic familiarity with AI chat interfaces"',
                'wrapper' => ['width' => '50'],
                'show_in_graphql' => true,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'example_difficulty',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'show_in_graphql' => true,
    ]);
}